name: test the things

on: [push, pull_request]

jobs:
  pylint:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - run: |
            python -m pip install --upgrade --quiet pip poetry
            poetry install
            poetry run pylint --rcfile=.pylintrc pvoutput
  poetry:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - run: |
            python -m pip install --upgrade --quiet pip poetry
            poetry build
  mypy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - run: |
            python -m pip install --upgrade --quiet pip poetry
            poetry install
            poetry run mypy pvoutput
